import streamlit as st
import sentry_sdk
from huggingface_hub import HfApi
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF

# 1. MONITORING SETUP (Sentry)
sentry_sdk.init(dsn=st.secrets["SENTRY_DSN"], traces_sample_rate=1.0)

st.set_page_config(page_title="Aura AI Architect", page_icon="⚖️", layout="wide")

# 2. FIXED HEARTBEAT LOGIC
def check_hf_status():
    try:
        # Standard API check to Hugging Face
        response = requests.get("https://huggingface.co/api/models", timeout=5)
        # FIX: We use .status_code to get the web response
        return "Online" if response.status_code == 200 else "Down"
    except:
        return "Offline"

# SIDEBAR STATUS DISPLAY
status = check_hf_status()
if status == "Online":
    st.sidebar.success(f"🟢 System Heartbeat: {status}")
else:
    st.sidebar.error(f"🔴 System Heartbeat: {status}")

# 3. HEADER & REGULATORY MAP
st.title("⚖️ Aura: Global AI Compliance Architect")
st.markdown("---")
st.subheader("🌐 Global AI Regulatory Risk Map")

map_data = pd.DataFrame({
    'Country': ['United States', 'China', 'European Union', 'United Kingdom', 'Canada', 'Brazil'],
    'Risk_Level': [3, 5, 5, 2, 3, 2],
    'Regulation': ['Executive Order 14110', 'Generative AI Measures', 'EU AI Act', 'AI Safety Institute', 'AIDA Bill', 'Bill 2338/23']
})
fig = px.choropleth(map_data, locations="Country", locationmode='country names', color="Risk_Level", hover_name="Regulation", color_continuous_scale=px.colors.sequential.Reds)
st.plotly_chart(fig, use_container_width=True)

# 4. HUGGING FACE AUDIT & PDF GENERATOR
st.subheader("🔍 Automated Model Audit")
model_id = st.text_input("Enter Hugging Face Model ID", "meta-llama/Llama-2-7b")

if st.button("Run Compliance Scan"):
    try:
        api = HfApi()
        model_info = api.model_info(model_id)
        lic = model_info.cardData.get('license', 'Unknown').upper()
        
        st.write(f"**Model Audited:** {model_id}")
        st.write(f"**License Found:** {lic}")
        
        # --- PDF GENERATION LOGIC ---
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(200, 10, txt="Aura AI Compliance Certificate", ln=1, align='C')
        pdf.ln(10)
        pdf.set_font("Arial", size=12)
        pdf.cell(200, 10, txt=f"Official Audit for Model ID: {model_id}", ln=1)
        pdf.cell(200, 10, txt=f"Compliance License: {lic}", ln=1)
        pdf.cell(200, 10, txt="Generated by: Aura Autonomous Compliance System", ln=1)
        
        # Convert PDF to bytes for download
        pdf_output = pdf.output(dest='S').encode('latin-1')
        
        st.download_button(
            label="📥 Download Compliance PDF", 
            data=pdf_output, 
            file_name=f"Aura_Audit_{model_id}.pdf", 
            mime="application/pdf"
        )
        
        if "MIT" in lic or "APACHE" in lic:
            st.success("✅ COMPLIANCE VERIFIED: High Transparency License.")
        else:
            st.warning("⚠️ COMPLIANCE ALERT: Restrictive or Proprietary License.")
            
    except Exception as e:
        sentry_sdk.capture_exception(e)
        st.error(f"Error Detected: {e}. Report sent to Sentry.")
